name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Node.js & Cordova
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create android-app com.kamu.euro2028 "Euro2028"
        rm -rf android-app/www/*
        rm -f android-app/config.xml
        
            # 5. Menyalin SEMUA file sekaligus ke folder aset aplikasi
            
    - name: Copy All Web Files & Config to App
      run: |
        cp -r * android-app/www/         # Menyalin semua file & folder ke dalam www/
        cp config.xml android-app/       # config.xml tetap wajib ditaruh di folder utama Android


    - name: Build APK File
      run: |
        cd android-app
        cordova platform add android
        cordova build android --release

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Android-Kamu
        path: android-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
